/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as DineroRouteImport } from './routes/dinero'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as MasRouteImport } from './routes/mas'
import { Route as PendientesRouteImport } from './routes/pendientes'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesClientIdRouteImport } from './routes/clientes.$clientId'
import { Route as MensajeClientIdRouteImport } from './routes/mensaje.$clientId'
import { Route as TrabajoJobIdRouteImport } from './routes/trabajo.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const DineroRoute = DineroRouteImport.update({
  id: '/dinero',
  path: '/dinero',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const MasRoute = MasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => rootRouteImport,
} as any)
const PendientesRoute = PendientesRouteImport.update({
  id: '/pendientes',
  path: '/pendientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClientIdRoute = ClientesClientIdRouteImport.update({
  id: '/clientes/$clientId',
  path: '/clientes/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const MensajeClientIdRoute = MensajeClientIdRouteImport.update({
  id: '/mensaje/$clientId',
  path: '/mensaje/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajoJobIdRoute = TrabajoJobIdRouteImport.update({
  id: '/trabajo/$jobId',
  path: '/trabajo/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dinero': typeof DineroRoute
  '/documentos': typeof DocumentosRoute
  '/gastos': typeof GastosRoute
  '/mas': typeof MasRoute
  '/pendientes': typeof PendientesRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/mensaje/$clientId': typeof MensajeClientIdRoute
  '/trabajo/$jobId': typeof TrabajoJobIdRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dinero': typeof DineroRoute
  '/documentos': typeof DocumentosRoute
  '/gastos': typeof GastosRoute
  '/mas': typeof MasRoute
  '/pendientes': typeof PendientesRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/mensaje/$clientId': typeof MensajeClientIdRoute
  '/trabajo/$jobId': typeof TrabajoJobIdRoute
  '/clientes': typeof ClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dinero': typeof DineroRoute
  '/documentos': typeof DocumentosRoute
  '/gastos': typeof GastosRoute
  '/mas': typeof MasRoute
  '/pendientes': typeof PendientesRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/mensaje/$clientId': typeof MensajeClientIdRoute
  '/trabajo/$jobId': typeof TrabajoJobIdRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/dinero'
    | '/documentos'
    | '/gastos'
    | '/mas'
    | '/pendientes'
    | '/clientes/$clientId'
    | '/mensaje/$clientId'
    | '/trabajo/$jobId'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/dinero'
    | '/documentos'
    | '/gastos'
    | '/mas'
    | '/pendientes'
    | '/clientes/$clientId'
    | '/mensaje/$clientId'
    | '/trabajo/$jobId'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/dinero'
    | '/documentos'
    | '/gastos'
    | '/mas'
    | '/pendientes'
    | '/clientes/$clientId'
    | '/mensaje/$clientId'
    | '/trabajo/$jobId'
    | '/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  DineroRoute: typeof DineroRoute
  DocumentosRoute: typeof DocumentosRoute
  GastosRoute: typeof GastosRoute
  MasRoute: typeof MasRoute
  PendientesRoute: typeof PendientesRoute
  ClientesClientIdRoute: typeof ClientesClientIdRoute
  MensajeClientIdRoute: typeof MensajeClientIdRoute
  TrabajoJobIdRoute: typeof TrabajoJobIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dinero': {
      id: '/dinero'
      path: '/dinero'
      fullPath: '/dinero'
      preLoaderRoute: typeof DineroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas': {
      id: '/mas'
      path: '/mas'
      fullPath: '/mas'
      preLoaderRoute: typeof MasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendientes': {
      id: '/pendientes'
      path: '/pendientes'
      fullPath: '/pendientes'
      preLoaderRoute: typeof PendientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clientId': {
      id: '/clientes/$clientId'
      path: '/clientes/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof ClientesClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensaje/$clientId': {
      id: '/mensaje/$clientId'
      path: '/mensaje/$clientId'
      fullPath: '/mensaje/$clientId'
      preLoaderRoute: typeof MensajeClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabajo/$jobId': {
      id: '/trabajo/$jobId'
      path: '/trabajo/$jobId'
      fullPath: '/trabajo/$jobId'
      preLoaderRoute: typeof TrabajoJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  DineroRoute: DineroRoute,
  DocumentosRoute: DocumentosRoute,
  GastosRoute: GastosRoute,
  MasRoute: MasRoute,
  PendientesRoute: PendientesRoute,
  ClientesClientIdRoute: ClientesClientIdRoute,
  MensajeClientIdRoute: MensajeClientIdRoute,
  TrabajoJobIdRoute: TrabajoJobIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
